//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEprop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mods
    {
        public int ModId { get; set; }
        public string ModPas { get; set; }
        public string ModLog { get; set; }
    }
}
