//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEprop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEsts
    {
        public int TestEstId { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public int TestScore { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
    }
}
